# -*- mode: ruby -*-
# vi: set ft=ruby :
# Use config.yaml for basic VM configuration.

require 'yaml'
dir = File.dirname(File.expand_path(__FILE__))
config_nodes = "#{dir}/config_multi-nodes.yaml"

if !File.exist?("#{config_nodes}")
  raise 'Configuration file is missing! Please make sure that the configuration exists and try again.'
end
vconfig = YAML::load_file("#{config_nodes}")

BRIDGE_NET = vconfig['vagrant_ip']
DOMAIN = vconfig['vagrant_domain_name']
RAM = vconfig['vagrant_memory']
MAC = vconfig['vagrant_mac']
SSH_PATH = './scripts/ssh_config.sh'

servers=[
  {
    :hostname => "ns1." + "#{DOMAIN}",
    :ram => 1024
  },
  {
    :hostname => "jenkins." + "#{DOMAIN}",
    :ram => "#{RAM}"
  }
]

for i in 0..servers.length-1
    servers[i][:ip] = "#{BRIDGE_NET}" + (1+i).to_s
    servers[i][:mac] = "#{MAC}" + (1+i).to_s
end


Vagrant.configure(2) do |config|
    config.vm.synced_folder ".", vconfig['vagrant_directory'], :mount_options => ["dmode=777", "fmode=666"]
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            if (machine[:hostname] == "ns1.devops.internal.com") then
                node.vm.box = "centos/7"
			    node.vm.box_version = "1905.1"
            else
			    node.vm.box = vconfig['vagrant_box']
			    node.vm.box_version = vconfig['vagrant_box_version']
            end
			node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.base_mac = machine[:mac]
            node.vm.provision :shell, path: "#{SSH_PATH}"
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
				vb.cpus = vconfig['vagrant_cpu']
				vb.memory = machine[:ram]
                vb.name = machine[:hostname]
            end
        end
    end
end
