- name: Set login opts
  set_fact:
    jenkins_login_opts: "-u {{ jenkins_admin_username }} -p {{ jenkins_admin_password }}"
  when: jenkins_admin_username and jenkins_admin_password

- name: Set jenkins host
  set_fact:
    jenkins_login_host: "http://{{ jenkins_admin_username }}:{{ jenkins_admin_password }}@{{ jenkins_hostname }}:{{ jenkins_http_port }}"
  when: jenkins_admin_username and jenkins_admin_password

- name: Copy create-credentials-config script
  copy:
    src:   "create-credentials-config.py"
    dest:  "{{ jenkins_home }}/create-credentials-config.py"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode:  0755

- name: Create username-password credentials config on Jenkins
  command: >
      python {{ jenkins_home }}/create-credentials-config.py userpass \
        -I {{ item.id }} -D {{ item.description }} \
        -U {{ item.user }} -P {{ item.pass }} \
        {{ jenkins_login_opts|default('') }}
  with_items: "{{ jenkins_job_creds_config }}"
  when: item.type == 'userpass'
  no_log: true

- name: Create ssh private credentials config on Jenkins
  command: >
      python {{ jenkins_home }}/create-credentials-config.py ssh-private-key \
        -I {{ item.id }} -D {{ item.description }} \
        -U {{ item.user }} -K "{{ item.key_file }}" \
        {{ jenkins_login_opts|default('') }}
  with_items: "{{ jenkins_job_creds_config }}"
  when: item.type == 'ssh-private-key'

# - name: Get crumb
#  command: >
#    curl --silent --cookie-jar /home/vagrant/jar "{{ jenkins_login_host }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
#  register: crumb
#
#- set_fact:
#    crumb={{ crumb.stdout }}
#
#- name: Create ssh private credentials config on Jenkins
#  command: >
#    curl --cookie /home/vagrant/jar -H "{{ crumb }}" -X POST '{{ jenkins_login_host }}/credentials/store/system/domain/_/createCredentials' \
#     --data-urlencode 'json={
#      "": "0",
#      "credentials": {
#        "scope": "GLOBAL",
#        "id": "{{ item.id }}",
#        "username": "{{ item.user }}",
#        "password": "",
#        "privateKeySource":{
#          "stapler-class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey.DirectEntryPrivateKeySource",
#          "privateKey": "{{ item.private }}"
#        },
#      "description": "{{ item.description }}",
#      "stapler-class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"}
#    }'
#  with_items: "{{ jenkins_ssh_keys }}"
#  when: item.type == 'ssh-private-key'

- name: Create secret text credentials config on Jenkins
  command: >
      python {{ jenkins_home }}/create-credentials-config.py secret-text \
        -I {{ item.id }} -D {{ item.description }} -T {{ item.secret }} \
        {{ jenkins_login_opts|default('') }}
  with_items: "{{ jenkins_job_creds_config }}"
  when: item.type == 'secret-text'
