---

- name: Create jenkins user .ssh directory
  file:
    path: "{{ jenkins_home }}/.ssh"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    state: directory

- name: Copy ssh PEM keys to jenkins user ssh directory
  copy:
    content: "{{ item.private_pem }}"
    dest: "{{ jenkins_home }}/.ssh/{{ item.keyname }}.pem"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0600
  when: item.private_pem|default(false)
  with_items: "{{ jenkins_ssh_keys }}"
  no_log: true

- name: Copy ssh PRIVATE keys to jenkins user ssh directory
  copy:
    content: "{{ item.private }}"
    dest: "{{ jenkins_home }}/.ssh/{{ item.keyname }}"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0600
  when: item.private|default(false)
  with_items: "{{ jenkins_ssh_keys }}"
  no_log: true

- name: Copy ssh PUBLIC keys to jenkins user ssh directory
  copy:
    content: "{{ item.public }}"
    dest: "{{ jenkins_home }}/.ssh/{{ item.keyname }}.pub"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0644
  with_items: "{{ jenkins_ssh_keys }}"

