---
# configuration
jenkins_job_builder_user_name: root
jenkins_job_builder_user_group: root

jenkins_job_builder_config_job_builder_allow_duplicates: False
jenkins_job_builder_config_job_builder_ignore_cache: True
jenkins_job_builder_config_job_builder_keep_descriptions: False
jenkins_job_builder_config_job_builder_recursive: False

jenkins_job_builder_config_jenkins_user: admin
jenkins_job_builder_config_jenkins_password: admin
jenkins_job_builder_config_jenkins_url: http://localhost:8080
jenkins_job_builder_config_jenkins_query_plugins_info: False

jenkins_job_builder_file_jobs_dest: /etc/jenkins_jobs/
jenkins_job_builder_file_jobs_group: jenkins
jenkins_job_builder_file_jobs_mode: "0755"
jenkins_job_builder_file_jobs_owner: jenkins
jenkins_job_builder_file_jobs_src: ../roles/jenkins_job_builder/templates/jobs

jenkins_job_builder_template_jenkins_jobs_ini_dest: /etc/jenkins_jobs/jenkins_jobs.ini
jenkins_job_builder_template_jenkins_jobs_ini_group: "{{ jenkins_job_builder_user_group }}"
jenkins_job_builder_template_jenkins_jobs_ini_mode: "0440"
jenkins_job_builder_template_jenkins_jobs_ini_owner: "{{ jenkins_job_builder_user_name }}"
jenkins_job_builder_template_jenkins_jobs_ini_src: etc/jenkins_jobs/jenkins_jobs.ini.j2

# installation
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"
jenkins_job_builder_pip_name: jenkins-job-builder

# handlers
jenkins_job_builder_handler_check_delay: 10
jenkins_job_builder_handler_check_retries: 3

# job config
ssh_credential: phamvuong
