- job:
    name: python-pipeline
    project-type: pipeline
    sandbox: true
    pipeline-scm:
      scm:
        - git:
            url: ssh://git@github.com/phamvuong/python_pipeline.git
            branch: master
            credentialsId: {{ ssh_credential }}
            clean: true
      triggers:
        - github-pull-request
      script-path: Jenkinsfile
      lightweight-checkout: true
