- job:
    name: python-pipeline
    project-type: pipeline
    sandbox: true
    pipeline-scm:
      scm:
        - git:
            url: https://github.com/phamvuong/python_pipeline.git
            branches:
              - ""
            credentials-id: phamvuong
            clean: true
      triggers:
        - github-pull-request
      script-path: Jenkinsfile_dev
      lightweight-checkout: true
