- name: Install common utils
  become: yes
  become_method: sudo
  yum:
    state: present
    name: ntp

- name: Copy resolve file for nameserver
  become: yes
  become_method: sudo
  template: src="resolv.conf" dest="/etc/resolv.conf" owner=root mode=644

- name: Add group "sysadmins" to remote server
  become: yes
  become_method: sudo
  group:
    name: sysadmins
    gid: 2010
    state: present

- name: Add user "sysadmin" to the remote server
  become: yes
  become_method: sudo
  user:
    name: sysadmin
    comment: "Privileged User"
    uid: 2001
    group: sysadmins
    append: yes
    shell: /bin/bash
    createhome: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
