---
- name: Configure jenkins machine
  become: yes
  become_method: sudo
  hosts: jenkins
  roles:
    - common
    - java
    - docker
    - jenkins

- import_playbook: jenkins_creds.yaml
- import_playbook: jenkins_job_builder.yaml
